jigsaw:
  build: .
  ports:
    - 9527:9527
  entrypoint:
    - java
    - -Dserver.port=9527
    - -Dspring.data.mongodb.uri=mongodb://mongodb/thoughtworks
    - -Dspring.profiles.active=production
    - -jar
    - /app.jar
  links:
    - mongodb

mongodb:
 image: mongo
 ports:
   - 27017:27017